# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today I Did / Today I Learnt
email:
description: >
  A collation of [what I have done](tid.md) each day at work and what I have learnt while coding.
  As well as [meet ups, courses, conferences](courses_etc.md) and other things I have been too.
  Plus [questions](questions.md) that come up for me as I am coding. The aim will be to overtime, answer these!
  There are many terms in coding/development/computer science that I don't know you, so there is also a [terms](terms.md) section.
baseurl: "tid_til" # the subpath of your site, e.g. /blog
url: "http://libbyschuknight.github.io"
twitter_username: schuknight
github_username:  libbyschuknight

# Build settings
include: ['_pages']
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title/
